### PR TITLE
Better perk availability check

### PR DESCRIPTION
**Pull request by kj415j45**
Reference: Bungie-net/api#1485, https://www.light.gg/db/items/3164743584/eye-of-sol/

### CODE REVIEW

**Comment by TheBrenny** [comment]
Wouldn't a better fix be to update the find to `firstWhereOrNull((p) => p.plugItemHash == plugHash && p.currentlyCanRoll)`? Elsewhere in the code, this should be the case, imo. Why look for perks that can't roll on the weapon (or roll on older versions only)?

**Comment by joaopmarquesini** [comment]
@TheBrenny I thought about that as well, but on a second thought, this could give false positives for weapons that could roll on previous seasons but can't anymore on the latest instance.
If I understood correctly, higher indexes will always be more recent.
is that the case @kj415j45 ?

**Comment by kj415j45** [comment]
> higher indexes will always be more recent.

I guess, yes. But bungie never said that 🤷🏼‍♂️. And actually we have no clue about the exactly perk pool unless we test it with Monte Carlo method.

**Comment by TheBrenny** [comment]
> this could give false positives for weapons that could roll on previous seasons but can't anymore on the latest instance

But then you'd hope that Bungie would update the API to reflect the current rollable perks, right? For example, if the weapon has perks on it from Season 2 that are no longer available, that instance of that weapon would still show those unrollable perks, but then only show hypothetical perks from the `currentlyCanRoll:true` perks.

That's only if I'm understanding this issue correctly?

**Comment by joaopmarquesini** [comment]
The do update @TheBrenny , but by addition, not substitution.
Let's take Eye of Sol for example.
You could roll Vorpal when it launched and now you can't anymore. They kept the canroll=true on index 0 (that was related to the first instance of it) and then added canRoll=false on the index 7 (that is the one version we have right now).
Using that approach you suggested would have us showing Vorpal as available when it shouldn't. i think I will need to go into a more complex route, by either passing the entire plug object or the index of the pen in the plug array to avoid showing the same perk as available twice.
Or maybe we can call it a day and go @kj415j45's route if Bungie confirms that higher index == latest info
Either way, this is already better than what we have now.

**Review by joaopmarquesini — APPROVED** [review]

**Comment by TheBrenny** [comment]
But `[0].canRoll` is false and `[7].canRoll` is true in the API. Regardless, we can assume that higher indexes == latest info, but what if they switch off a higher index in favour of an older perk, or switch on older perks to expand the perk pool?

You're right as an interim, this is *a* fix, but I think the better solution would be to check and only display `canRoll: true`?

image

**Pull request merged**
